### ISSUE TITLE
"no required module provides package github.com/drud/ddev/pkg/ddevapp" error

### ISSUE THREAD

**Issue by mandrasch** [iammati/ddev-ui#1]
Hi, nice project! I wanted to try it out, but I got the following errors after build:

```
app.go:7:2: no required module provides package github.com/drud/ddev/pkg/ddevapp: go.mod file not found in current directory or any parent directory; see 'go help modules'
app.go:8:5: no required module provides package github.com/drud/ddev/pkg/exec: go.mod file not found in current directory or any parent directory; see 'go help modules'
app.go:10:2: no required module provides package github.com/gin-contrib/cors: go.mod file not found in current directory or any parent directory; see 'go help modules'
app.go:11:2: no required module provides package github.com/gin-gonic/gin: go.mod file not found in current directory or any parent directory; see 'go help modules'
app.go:13:2: no required module provides package github.com/zserge/lorca: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

`ddev pnpm run serve` results in the following:

![image](https://user-images.githubusercontent.com/777278/151872900-7b653526-a408-42c4-b9ff-8ef5a9bfa530.png)

My version/OS:
```
/ddev-ui % go version
go version go1.17.6 darwin/arm64

/ddev-ui % ddev -v
ddev version v1.18.2

MacBook with M1 processor, OS: 11.5.2 Big Sur
```

Do you have any tipp to get this running? (I have zero experience with go)

Thanks in advance & cheers!

**Comment by iammati** [comment]
Just pushed a fix since the `go.mod` file was missing, my bad 😅
You may simply pull and run `go install && go run app.go` which should install necessary deps from the `go.mod` AFAIK and run the actual `app.go`.

I'm also a golang beginner btw no worries :)

**Comment by mandrasch** [comment]
Nice, thanks, the app now popped up as well with ` go run app.go`. :+1: :+1: 

But the fetch problem remained:   
```
http://172.21.128.32:8080/api/router_status
Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
```

**Comment by iammati** [comment]
Yeah you should change the IP inside `ddev-ui.config.js` to the one of your local server (which you can retrieve using `hostname -I` in the most cases)

**Comment by mandrasch** [comment]
Thanks! (Thought the ip address was gathered automatically somehow ;-)). With the config change to my local ip address, `ddev pnpm run build`,  `go install` &  `go run app.go` the ddev router info is now set to "healthy" :+1:

Project list returns an empty list though, but maybe I can debug this myself in the next days. Thanks for your support!

![image](https://user-images.githubusercontent.com/777278/151883794-f09679e1-c47e-4205-bfef-69cc4aaed307.png)

**Comment by mandrasch** [comment]
Ah okay, I see:

```
		// List of ddev projects
		v1.GET("/list_projects", func(c *gin.Context) {
			DdevBin := "/usr/local/bin/ddev"
			jsonOutput, err := exec.RunHostCommand(DdevBin, "list", "-j")
```

My DDEV path is not /usr/local/bin/ddev : 
```
/ddev-ui % /usr/local/bin/ddev     
zsh: no such file or directory: /usr/local/bin/ddev
/ddev-ui % which ddev
/opt/homebrew/bin/ddev
/ddev-ui % 
```

**Comment by iammati** [comment]
Glad to see you get through it! The whole repository is still in "experimental mode". Stuff which happens here are and for sure will break in future commits until (if at all) the whole thing reach a stable build. :)

AFAIK this should be seen as some proposal/alternative instead of going go-native solution only as you can read from here: https://github.com/drud/ddev/issues/2110

**Comment by mandrasch** [comment]
I found this repo initially via the #2110 discussion. :+1: Excited to see how this (and the UI discussion) will turn out in future!
